# Generated by Django 4.0 on 2024-03-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='Power',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cars',
            name='acceleration_to_100',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cars',
            name='max_speed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cars',
            name='type_of_drive',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='cars',
            name='type_of_gsb',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='cars',
            name='Car',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='Email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='Name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
