# Generated by Django 4.0 on 2024-04-01 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('rent', '0002_cars_power_cars_acceleration_to_100_cars_max_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetime',
            name='CarID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cars'),
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
