# Generated by Django 4.0 on 2024-04-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car', models.CharField(default='', max_length=255)),
                ('Power', models.PositiveIntegerField(default=0)),
                ('acceleration_to_100', models.FloatField(default=0)),
                ('max_speed', models.PositiveIntegerField(default=0)),
                ('type_of_gsb', models.CharField(default='', max_length=14)),
                ('type_of_drive', models.CharField(default='', max_length=8)),
            ],
        ),
    ]
